version: '3.7'
services:
  app:
    image: todos-backend:v3
    depends_on:
      - db
    ports:
      - '3000:3000'
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: demo
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    name: pgdata

    